<?php

/**
 * @file
 * The entity_reference_entity_modify hook implementations.
 */

/**
 * Implements hook_field_widget_info_alter().
 */
function entity_reference_entity_modify_field_widget_info_alter(array &$info): void {
  $info['entity_reference_autocomplete_tags']['field_types'][] = 'entity_reference_entity_override';
  $info['entity_reference_autocomplete']['field_types'][] = 'entity_reference_entity_override';
  $info['options_buttons']['field_types'][] = 'entity_reference_entity_override';
  $info['options_select']['field_types'][] = 'entity_reference_entity_override';
}
